# Generated by Django 4.2.4 on 2023-09-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogTecnoWave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="New Entry", max_length=255),
        ),
    ]
