# Generated by Django 4.2.5 on 2023-09-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogTecnoWave", "0008_alter_post_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
